name: Pull request check

on:
  pull_request

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Install and build 🔧
      - run: npm ci
      - run: npm run build
